
package eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IRT01T", targetNamespace = "http://irt01t.wsbeans.iseries", wsdlLocation = "http://62.214.69.250:10010/web/services/IRT01T?wsdl")
public class IRT01T
    extends Service
{

    private final static URL IRT01T_WSDL_LOCATION;
    private final static WebServiceException IRT01T_EXCEPTION;
    private final static QName IRT01T_QNAME = new QName("http://irt01t.wsbeans.iseries", "IRT01T");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://62.214.69.250:10010/web/services/IRT01T?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IRT01T_WSDL_LOCATION = url;
        IRT01T_EXCEPTION = e;
    }

    public IRT01T() {
        super(__getWsdlLocation(), IRT01T_QNAME);
    }

    public IRT01T(WebServiceFeature... features) {
        super(__getWsdlLocation(), IRT01T_QNAME, features);
    }

    public IRT01T(URL wsdlLocation) {
        super(wsdlLocation, IRT01T_QNAME);
    }

    public IRT01T(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IRT01T_QNAME, features);
    }

    public IRT01T(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRT01T(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRT01TPortType
     */
    @WebEndpoint(name = "IRT01THttpSoap11Endpoint")
    public IRT01TPortType getIRT01THttpSoap11Endpoint() {
        return super.getPort(new QName("http://irt01t.wsbeans.iseries", "IRT01THttpSoap11Endpoint"), IRT01TPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRT01TPortType
     */
    @WebEndpoint(name = "IRT01THttpSoap11Endpoint")
    public IRT01TPortType getIRT01THttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://irt01t.wsbeans.iseries", "IRT01THttpSoap11Endpoint"), IRT01TPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IRT01T_EXCEPTION!= null) {
            throw IRT01T_EXCEPTION;
        }
        return IRT01T_WSDL_LOCATION;
    }

}
