
package eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRT01TPortType", targetNamespace = "http://irt01t.wsbeans.iseries")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRT01TPortType {


    /**
     * 
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "irt01_XML", action = "urn:irt01_XML")
    @WebResult(targetNamespace = "http://irt01t.wsbeans.iseries/xsd")
    @RequestWrapper(localName = "irt01_XML", targetNamespace = "http://irt01t.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t.Irt01XML")
    @ResponseWrapper(localName = "irt01_XMLResponse", targetNamespace = "http://irt01t.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t.Irt01XMLResponse")
    public String irt01XML(
        @WebParam(name = "args0", targetNamespace = "http://irt01t.wsbeans.iseries/xsd")
        IRT01Input args0);

    /**
     * 
     * @param args0
     * @return
     *     returns eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t.IRT01Result
     */
    @WebMethod(action = "urn:irt01")
    @WebResult(targetNamespace = "http://irt01t.wsbeans.iseries/xsd")
    @RequestWrapper(localName = "irt01", targetNamespace = "http://irt01t.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t.Irt01")
    @ResponseWrapper(localName = "irt01Response", targetNamespace = "http://irt01t.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt01t.Irt01Response")
    public IRT01Result irt01(
        @WebParam(name = "args0", targetNamespace = "http://irt01t.wsbeans.iseries/xsd")
        IRT01Input args0);

}
