
package eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IRT02E", targetNamespace = "http://irt02e.wsbeans.iseries", wsdlLocation = "http://62.214.69.250:10010/web/services/IRT02E?wsdl")
public class IRT02E
    extends Service
{

    private final static URL IRT02E_WSDL_LOCATION;
    private final static WebServiceException IRT02E_EXCEPTION;
    private final static QName IRT02E_QNAME = new QName("http://irt02e.wsbeans.iseries", "IRT02E");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://62.214.69.250:10010/web/services/IRT02E?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IRT02E_WSDL_LOCATION = url;
        IRT02E_EXCEPTION = e;
    }

    public IRT02E() {
        super(__getWsdlLocation(), IRT02E_QNAME);
    }

    public IRT02E(WebServiceFeature... features) {
        super(__getWsdlLocation(), IRT02E_QNAME, features);
    }

    public IRT02E(URL wsdlLocation) {
        super(wsdlLocation, IRT02E_QNAME);
    }

    public IRT02E(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IRT02E_QNAME, features);
    }

    public IRT02E(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRT02E(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRT02EPortType
     */
    @WebEndpoint(name = "IRT02EHttpSoap11Endpoint")
    public IRT02EPortType getIRT02EHttpSoap11Endpoint() {
        return super.getPort(new QName("http://irt02e.wsbeans.iseries", "IRT02EHttpSoap11Endpoint"), IRT02EPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRT02EPortType
     */
    @WebEndpoint(name = "IRT02EHttpSoap11Endpoint")
    public IRT02EPortType getIRT02EHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://irt02e.wsbeans.iseries", "IRT02EHttpSoap11Endpoint"), IRT02EPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IRT02E_EXCEPTION!= null) {
            throw IRT02E_EXCEPTION;
        }
        return IRT02E_WSDL_LOCATION;
    }

}
