
package eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRT02EPortType", targetNamespace = "http://irt02e.wsbeans.iseries")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRT02EPortType {


    /**
     * 
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "irt02_XML", action = "urn:irt02_XML")
    @WebResult(targetNamespace = "http://irt02e.wsbeans.iseries/xsd")
    @RequestWrapper(localName = "irt02_XML", targetNamespace = "http://irt02e.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e.Irt02XML")
    @ResponseWrapper(localName = "irt02_XMLResponse", targetNamespace = "http://irt02e.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e.Irt02XMLResponse")
    public String irt02XML(
        @WebParam(name = "args0", targetNamespace = "http://irt02e.wsbeans.iseries/xsd")
        IRT02Input args0);

    /**
     * 
     * @param args0
     * @return
     *     returns eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e.IRT02Result
     */
    @WebMethod(action = "urn:irt02")
    @WebResult(targetNamespace = "http://irt02e.wsbeans.iseries/xsd")
    @RequestWrapper(localName = "irt02", targetNamespace = "http://irt02e.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e.Irt02")
    @ResponseWrapper(localName = "irt02Response", targetNamespace = "http://irt02e.wsbeans.iseries/xsd", className = "eu.artofcoding.retoure.store.aktivshop.wsclient.irt02e.Irt02Response")
    public IRT02Result irt02(
        @WebParam(name = "args0", targetNamespace = "http://irt02e.wsbeans.iseries/xsd")
        IRT02Input args0);

}
