
package eu.artofcoding.retoure.store.aktivshop.wsclient.irt02t;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IRT02T", targetNamespace = "http://irt02t.wsbeans.iseries", wsdlLocation = "http://62.214.69.250:10010/web/services/IRT02T?wsdl")
public class IRT02T
    extends Service
{

    private final static URL IRT02T_WSDL_LOCATION;
    private final static WebServiceException IRT02T_EXCEPTION;
    private final static QName IRT02T_QNAME = new QName("http://irt02t.wsbeans.iseries", "IRT02T");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://62.214.69.250:10010/web/services/IRT02T?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IRT02T_WSDL_LOCATION = url;
        IRT02T_EXCEPTION = e;
    }

    public IRT02T() {
        super(__getWsdlLocation(), IRT02T_QNAME);
    }

    public IRT02T(WebServiceFeature... features) {
        super(__getWsdlLocation(), IRT02T_QNAME, features);
    }

    public IRT02T(URL wsdlLocation) {
        super(wsdlLocation, IRT02T_QNAME);
    }

    public IRT02T(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IRT02T_QNAME, features);
    }

    public IRT02T(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRT02T(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRT02TPortType
     */
    @WebEndpoint(name = "IRT02THttpSoap11Endpoint")
    public IRT02TPortType getIRT02THttpSoap11Endpoint() {
        return super.getPort(new QName("http://irt02t.wsbeans.iseries", "IRT02THttpSoap11Endpoint"), IRT02TPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRT02TPortType
     */
    @WebEndpoint(name = "IRT02THttpSoap11Endpoint")
    public IRT02TPortType getIRT02THttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://irt02t.wsbeans.iseries", "IRT02THttpSoap11Endpoint"), IRT02TPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IRT02T_EXCEPTION!= null) {
            throw IRT02T_EXCEPTION;
        }
        return IRT02T_WSDL_LOCATION;
    }

}
