
package eu.artofcoding.retoure.store.aktivshop.wsclient.irt01e;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IRT01E", targetNamespace = "http://irt01e.wsbeans.iseries", wsdlLocation = "http://62.214.69.250:10010/web/services/IRT01E?wsdl")
public class IRT01E
    extends Service
{

    private final static URL IRT01E_WSDL_LOCATION;
    private final static WebServiceException IRT01E_EXCEPTION;
    private final static QName IRT01E_QNAME = new QName("http://irt01e.wsbeans.iseries", "IRT01E");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://62.214.69.250:10010/web/services/IRT01E?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IRT01E_WSDL_LOCATION = url;
        IRT01E_EXCEPTION = e;
    }

    public IRT01E() {
        super(__getWsdlLocation(), IRT01E_QNAME);
    }

    public IRT01E(WebServiceFeature... features) {
        super(__getWsdlLocation(), IRT01E_QNAME, features);
    }

    public IRT01E(URL wsdlLocation) {
        super(wsdlLocation, IRT01E_QNAME);
    }

    public IRT01E(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IRT01E_QNAME, features);
    }

    public IRT01E(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRT01E(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRT01EPortType
     */
    @WebEndpoint(name = "IRT01EHttpSoap11Endpoint")
    public IRT01EPortType getIRT01EHttpSoap11Endpoint() {
        return super.getPort(new QName("http://irt01e.wsbeans.iseries", "IRT01EHttpSoap11Endpoint"), IRT01EPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRT01EPortType
     */
    @WebEndpoint(name = "IRT01EHttpSoap11Endpoint")
    public IRT01EPortType getIRT01EHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://irt01e.wsbeans.iseries", "IRT01EHttpSoap11Endpoint"), IRT01EPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IRT01E_EXCEPTION!= null) {
            throw IRT01E_EXCEPTION;
        }
        return IRT01E_WSDL_LOCATION;
    }

}
