
package eu.artofcoding.retoure.delivery.dhl.amsel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RpPartnerType", targetNamespace = "https://amsel.dpwn.net/abholportal/gw/lp/schema/1.0/var3ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RpPartnerType {


    /**
     * 
     * @param parameters
     * @return
     *     returns eu.artofcoding.retoure.delivery.dhl.amsel.BookLabelResponseType
     */
    @WebMethod(operationName = "BookLabel")
    @WebResult(name = "BookLabelResponse", targetNamespace = "https://amsel.dpwn.net/abholportal/gw/lp/schema/1.0/var3bl", partName = "parameters")
    public BookLabelResponseType bookLabel(
        @WebParam(name = "BookLabelRequest", targetNamespace = "https://amsel.dpwn.net/abholportal/gw/lp/schema/1.0/var3bl", partName = "parameters")
        BookLabelRequestType parameters);

}
